name: Manual trigger
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet"
        default: "World"
jobs:
    hello:
        runs-on: [self-hosted, linux, ARM64]
        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"